[build-system]
requires = ["setuptools>=83.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "xxtrain"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.1",
    "opencv-python>=5.0.0.93",
    "Pillow>=12.3.0",
    "platformdirs>=4.11.0",
    "ruamel.yaml>=0.19.1",
    "tqdm>=4.70.0",
    "ultralytics>=8.4.110",
]

[project.optional-dependencies]
dev = ["PyYAML>=6.0.3", "pycocotools>=2.0.11", "ruff>=0.15.22"]

[project.scripts]
xxtrain = "xxtrain.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

# https://beta.ruff.rs/docs/settings/
[tool.ruff]
# https://beta.ruff.rs/docs/rules/
line-length = 120
# Exclude a variety of commonly ignored directories.
respect-gitignore = true

[tool.ruff.lint]
select = ["E", "W", "F", "I", "UP"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
quote-style = "single"
line-ending = "lf"
skip-magic-trailing-comma = true
docstring-code-format = true
