agent {
    worker_id: "xxtrain-training-01"
    python_binary: "/opt/xxtrain-agent/bin/python"
    package_manager {
        type: pip
    }
    venvs_dir: "/var/lib/clearml-agent/venvs-builds"
    venvs_cache {
        path: "/var/lib/clearml-agent/venvs-cache"
    }
    vcs_cache {
        enabled: false
        path: "/var/lib/clearml-agent/vcs-cache"
    }
    pip_download_cache {
        enabled: true
        path: "/var/lib/clearml-agent/pip-download-cache"
    }
}
